# Generated by Django 3.2.6 on 2021-09-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='coarse_image',
            field=models.ImageField(upload_to='course.png'),
        ),
    ]
