# Generated by Django 3.2.6 on 2021-09-07 08:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_course_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_module',
            name='video_url',
        ),
        migrations.AddField(
            model_name='course_module',
            name='course_video',
            field=models.FileField(default=django.utils.timezone.now, upload_to='video/%y'),
            preserve_default=False,
        ),
    ]
