# Generated by Django 3.2.6 on 2021-09-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210907_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_module',
            name='course_video',
        ),
        migrations.AddField(
            model_name='course_module',
            name='video',
            field=models.FileField(default=0, upload_to='video'),
            preserve_default=False,
        ),
    ]
