# Generated by Django 3.2.6 on 2021-09-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210907_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_module',
            name='video',
            field=models.FileField(upload_to='video/%y'),
        ),
    ]
