# Generated by Django 3.2.6 on 2021-09-08 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_course_module_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('video', models.FileField(upload_to='video/%y')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.course')),
            ],
        ),
        migrations.RemoveField(
            model_name='course_module',
            name='course',
        ),
        migrations.DeleteModel(
            name='Destinatiom',
        ),
        migrations.DeleteModel(
            name='course_module',
        ),
    ]
