# Generated by Django 3.2.6 on 2021-09-09 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_course_video_course_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='course_name',
            new_name='course',
        ),
    ]
