# Generated by Django 3.2.6 on 2021-10-04 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0002_alter_question_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='Answers',
        ),
    ]
