# Generated by Django 3.2.6 on 2021-10-05 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Questions', '0003_rename_answer_answers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answers',
            options={'verbose_name_plural': 'Answers'},
        ),
    ]
