# Generated by Django 3.2.6 on 2021-10-03 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizes'},
        ),
    ]
