# Generated by Django 3.2.6 on 2021-10-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizes', '0003_auto_20211003_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='time',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='number_of_questions',
            field=models.IntegerField(help_text='Duration of quiz in minutes'),
        ),
    ]
