# Generated by Django 3.2.6 on 2021-10-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizes', '0004_auto_20211003_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time',
            field=models.IntegerField(default=10, help_text='Duration of quiz in minutes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='number_of_questions',
            field=models.IntegerField(),
        ),
    ]
