# Generated by Django 3.2.6 on 2021-10-05 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizes', '0005_auto_20211003_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='requied_score_to_pass',
            new_name='required_score_to_pass',
        ),
    ]
